SEARCH_BAR = '//XCUIElementTypeOther[@name="Search properties, region"]/XCUIElementTypeOther[1]'
NOTIFICATION = '//XCUIElementTypeButton[@name="Close"]'
ENTER_DEST_FIELD = 'xpath=//XCUIElementTypeOther[@name="Enter destination, web dialogue"]/XCUIElementTypeOther[3]'
KOLKATA_OPTION = 'xpath=//XCUIElementTypeOther[@name="Kolkata West Bengal, India, Kolkata West Bengal, India"]'
STAY_DURATION = 'xpath=//XCUIElementTypeOther[@name="How long do you want to stay?"]/XCUIElementTypeOther[2]'
DONE_BUTTON = 'xpath=//XCUIElementTypeButton[@name="Done"]'
SEARCH_BUTTON = 'xpath=//XCUIElementTypeButton[@name="Search"]'
SORT_BUTTON = 'xpath=//XCUIElementTypeButton[@name="Sort"]'

general_settings='//XCUIElementTypeButton[@name="com.apple.settings.general"]'
about_phone='//XCUIElementTypeCell[@name="About"]'
ios_version = '//XCUIElementTypeStaticText[@name="18.2"]'
name = '//XCUIElementTypeStaticText[@name="iPhone"]'
about_back_button = '//XCUIElementTypeButton[@name="Back"]'
general_to_settings_button = '//XCUIElementTypeButton[@name="Settings"]'
settings_home = '//XCUIElementTypeStaticText[@name="Apple Account"]'

INTEGER_A_FIELD = '//XCUIElementTypeTextField[@name="IntegerA"]'
INTEGER_B_FIELD = '//XCUIElementTypeTextField[@name="IntegerB"]'
COMPUTE_SUM_BUTTON = '//XCUIElementTypeButton[@name="ComputeSumButton"]'
ANSWER_FIELD = '//XCUIElementTypeStaticText[@name="Answer"]'
SHOW_ALERT_BUTTON = '//XCUIElementTypeStaticText[@name="show alert"]'
COOL_ALERT_TITLE = '//XCUIElementTypeAlert[@name="Cool title"]'
SLIDER_LOCATOR = '//XCUIElementTypeSlider[@name="AppElem"]'

